### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by alikemalocalan**
fixed libs no found

### CODE REVIEW

**Comment by pires** [comment]
Dependencies were not found because you didn't follow [the instructions](https://github.com/pires/spring-boot-shiro-orientdb#spring-data-hack).

Now, I like the idea of adopting the (now!) existing official artifacts but I'd ask for updating the documentation too and make sure tests pass.

**Review by pires — CHANGES_REQUESTED** [review]
Dependencies were not found because you didn't follow [the instructions](https://github.com/pires/spring-boot-shiro-orientdb#spring-data-hack).

Now, I like the idea of adopting the (now!) existing official artifacts but I'd ask for updating the documentation too and make sure tests pass.

**Comment by alikemalocalan** [comment]
I'm just saying it's information:

Yuor dependencies and  your instructions is very old  and now not found. it's moved "com.orientechnologies".
that's it: 
https://mvnrepository.com/artifact/com.orientechnologies/spring-boot-orientdb-autoconfigure/0.11

**Comment by pires** [comment]
OK 👍

**Pull request closed without merging**
